<a href="https://colab.research.google.com/github/karankeshav/python-assignment/blob/main/26_feb_numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY ASSIGNMENT

###Consider the below code to answer further questions:
import numpy as np


list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]


array_list = np.array(object = list_)

###Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

###Ans.
Yes, there is difference between list_ and array_list.
list_ is noramal datatype(list) whereas array_list is numpy data type which is fast and consume less memory than normal datatype.



In [4]:
import numpy as np
list_=[  '1' , '2', '3' , '4' , '5' ]
array_list=np.array([  '1' , '2' , '3' , '4' , '5' ])
print(list_,type(list_))
print(array_list,type(array_list))

['1', '2', '3', '4', '5'] <class 'list'>
['1' '2' '3' '4' '5'] <class 'numpy.ndarray'>


###Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.


###Ans.


In [25]:
list_=['1','2','3','4','5']
array_list=np.array(['1','2','3','4','5'])
for i in list_:
  print(i,type(i))
for i in array_list:
  print(i,type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


###Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [26]:
list_=[1,2,3,4,5]
array_list=np.array([1,2,3,4,5])

#Yes,there is differnce in datatype of above list_ and array_list

'let us see in brief through  coding below'

'let us see in brief through  coding below'

In [27]:
for i in list_:
  print(i,type(i))

for i in array_list:
  print(i,type(i))

1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
4 <class 'int'>
5 <class 'int'>
1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

###Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape

(ii) size


###Ans.


In [15]:
num_list=[[1,2,3],[4,5,6]]
num_array=np.array(([1,2,3],[4,5,6]))
print(num_array.shape)
print(num_array.size)

(2, 3)
6


###Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.


###Ans.

In [18]:
import numpy as np
array=np.zeros((3,3))
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###Q6. Create an identity matrix of shape (5,5) using numpy functions?


###Ans.

In [20]:
array=np.identity((5))
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
